#!/usr/bin/env bash

function log() {
  local LEVEL=INFO
  [[ $# -gt 2 && $1 = "-l" ]] && LEVEL=$2 && shift 2
  echo "[${LEVEL}]: $@"
}

function gpg_rk() {
  log "getting gpg keys [$@]"
  gpg --recv-keys "$@" &> /dev/null
}

function gpg_clean() {
  log "cleaning gpg homedig"
  rm -rf ~/.gnupg
}

function gpg_parse_keys() {
  curl --silent --show-error --location "$1" | gpg --with-fingerprint --with-colons | grep "^fpr" | cut -d: -f10
}

function apache_dl_url() {
  echo -n "https://www.apache.org/dyn/closer.lua?action=download&filename=$1"
}

function apache_dist_url() {
  echo -n "https://www.apache.org/dist/$1"
}

function dl_and_verify() {
  local URL=$1
  local DEST=$2
  local URL_SIG=${3:-${URL}.asc}
  log "downloading ${URL} to ${DEST} (sig: ${URL_SIG})"
  curl --silent --show-error --location ${URL} --output ${DEST}
  curl --silent --show-error --location ${URL_SIG} --output ${DEST}.asc
  gpg --verify ${DEST}.asc ${DEST} &> /dev/null
  rm -f ${DEST}.asc
  log "sig ok"
}

function yum_clean() {
  yum clean all &> /dev/null
  rm -rf /var/cache/yum/*
}

function yumu() {
  yum update -y
  yum_clean
}

function yumi() {
  yum install -y "$@"
  yum_clean
  log "installed packages $@"
}

function yumgi() {
  yum group install -y "$@"
  yum_clean
  log "installed package groups $@"
}
